"""Add date_of_birth to ChildProfile

Revision ID: 0b44915641b4
Revises: c6e1103414c8
Create Date: 2026-08-31 06:31:17.822475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b44915641b4'
down_revision: Union[str, Sequence[str], None] = 'c6e1103414c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child_profiles', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.drop_column('child_profiles', 'primary_condition')
    op.drop_column('child_profiles', 'age_range')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child_profiles', sa.Column('age_range', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('child_profiles', sa.Column('primary_condition', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('child_profiles', 'date_of_birth')
    # ### end Alembic commands ###
