"""Add location fields to User

Revision ID: 2d8a946eebf1
Revises: 7acb644b2882
Create Date: 2026-09-26 08:03:20.590386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d8a946eebf1'
down_revision: Union[str, Sequence[str], None] = '7acb644b2882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city', sa.String(), nullable=True))
    op.add_column('user', sa.Column('pincode', sa.String(), nullable=True))
    op.add_column('user', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lng')
    op.drop_column('user', 'lat')
    op.drop_column('user', 'pincode')
    op.drop_column('user', 'city')
    # ### end Alembic commands ###
