"""Add skill_area and independence_score

Revision ID: 438531db8bd3
Revises: fe9a19af7b4b
Create Date: 2026-09-26 15:29:01.002268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '438531db8bd3'
down_revision: Union[str, Sequence[str], None] = 'fe9a19af7b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_sessions', sa.Column('skill_area', sa.String(), nullable=True))
    op.add_column('activity_sessions', sa.Column('independence_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_sessions', 'independence_score')
    op.drop_column('activity_sessions', 'skill_area')
    # ### end Alembic commands ###
