"""Add session types and group sessions

Revision ID: 43f4b8b6eede
Revises: edf62369397d
Create Date: 2026-09-19 19:14:02.053868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f4b8b6eede'
down_revision: Union[str, Sequence[str], None] = 'edf62369397d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapist_group_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('therapist_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.String(), nullable=False),
    sa.Column('scheduled_time', sa.String(), nullable=False),
    sa.Column('duration_mins', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('current_participants', sa.Integer(), nullable=False),
    sa.Column('video_room_id', sa.String(), nullable=True),
    sa.Column('video_room_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapist_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_session_enrollments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('group_session_id', sa.String(), nullable=False),
    sa.Column('parent_user_id', sa.String(), nullable=False),
    sa.Column('parent_name', sa.String(), nullable=False),
    sa.Column('parent_email', sa.String(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_session_id'], ['therapist_group_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_session_enrollments_parent_user_id'), 'group_session_enrollments', ['parent_user_id'], unique=False)
    op.add_column('therapist_bookings', sa.Column('session_type', sa.String(), server_default='child_therapy', nullable=False))
    op.add_column('therapist_profiles', sa.Column('offers_child_therapy', sa.Boolean(), nullable=True))
    op.add_column('therapist_profiles', sa.Column('offers_caregiver_training', sa.Boolean(), nullable=True))
    op.add_column('therapist_profiles', sa.Column('offers_group_training', sa.Boolean(), nullable=True))
    op.add_column('therapist_profiles', sa.Column('caregiver_price_online', sa.Integer(), nullable=True))
    op.add_column('therapist_profiles', sa.Column('caregiver_price_offline', sa.Integer(), nullable=True))
    op.add_column('therapist_profiles', sa.Column('group_price_online', sa.Integer(), nullable=True))
    op.add_column('therapist_profiles', sa.Column('group_price_offline', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('therapist_profiles', 'group_price_offline')
    op.drop_column('therapist_profiles', 'group_price_online')
    op.drop_column('therapist_profiles', 'caregiver_price_offline')
    op.drop_column('therapist_profiles', 'caregiver_price_online')
    op.drop_column('therapist_profiles', 'offers_group_training')
    op.drop_column('therapist_profiles', 'offers_caregiver_training')
    op.drop_column('therapist_profiles', 'offers_child_therapy')
    op.drop_column('therapist_bookings', 'session_type')
    op.drop_index(op.f('ix_group_session_enrollments_parent_user_id'), table_name='group_session_enrollments')
    op.drop_table('group_session_enrollments')
    op.drop_table('therapist_group_sessions')
    # ### end Alembic commands ###
