"""Add micro consultations

Revision ID: 7acb644b2882
Revises: e2659d8a0077
Create Date: 2026-09-20 20:14:02.158455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7acb644b2882'
down_revision: Union[str, Sequence[str], None] = 'e2659d8a0077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('micro_consultations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=False),
    sa.Column('therapist_id', sa.String(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('price_inr', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapist_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_micro_consultations_id'), 'micro_consultations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_micro_consultations_id'), table_name='micro_consultations')
    op.drop_table('micro_consultations')
    # ### end Alembic commands ###
