"""Add coaching models

Revision ID: 8206e051d141
Revises: 438531db8bd3
Create Date: 2026-09-26 16:26:19.567566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8206e051d141'
down_revision: Union[str, Sequence[str], None] = '438531db8bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaching_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=False),
    sa.Column('coach_id', sa.String(), nullable=False),
    sa.Column('sender_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.String(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['therapist_profiles.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coaching_messages_coach_id'), 'coaching_messages', ['coach_id'], unique=False)
    op.create_index(op.f('ix_coaching_messages_id'), 'coaching_messages', ['id'], unique=False)
    op.create_index(op.f('ix_coaching_messages_parent_id'), 'coaching_messages', ['parent_id'], unique=False)
    op.add_column('user', sa.Column('active_coach_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('coaching_subscription_status', sa.String(), nullable=True))
    op.add_column('user', sa.Column('coaching_subscription_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'user', 'therapist_profiles', ['active_coach_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'coaching_subscription_id')
    op.drop_column('user', 'coaching_subscription_status')
    op.drop_column('user', 'active_coach_id')
    op.drop_index(op.f('ix_coaching_messages_parent_id'), table_name='coaching_messages')
    op.drop_index(op.f('ix_coaching_messages_id'), table_name='coaching_messages')
    op.drop_index(op.f('ix_coaching_messages_coach_id'), table_name='coaching_messages')
    op.drop_table('coaching_messages')
    # ### end Alembic commands ###
