"""Add text_note to activity_sessions

Revision ID: 8c2ac3e0f1b3
Revises: b70081a88e41
Create Date: 2026-08-16 21:39:00.875177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c2ac3e0f1b3'
down_revision: Union[str, Sequence[str], None] = 'b70081a88e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_sessions', sa.Column('text_note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_sessions', 'text_note')
    # ### end Alembic commands ###
