"""add session_type to availability

Revision ID: 934c5604105e
Revises: 43f4b8b6eede
Create Date: 2026-09-19 19:47:30.303961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '934c5604105e'
down_revision: Union[str, Sequence[str], None] = '43f4b8b6eede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therapist_availability', sa.Column('session_type', sa.String(), server_default='child_therapy', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('therapist_availability', 'session_type')
    # ### end Alembic commands ###
