"""add_video_room_url

Revision ID: 9e998c23caaf
Revises: aed45a4fd845
Create Date: 2026-09-15 12:01:14.653572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e998c23caaf'
down_revision: Union[str, Sequence[str], None] = 'aed45a4fd845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therapist_bookings', sa.Column('video_room_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('therapist_bookings', 'video_room_url')
    # ### end Alembic commands ###
