"""add_razorpay_account_id

Revision ID: a94fcf6c31f4
Revises: 9e998c23caaf
Create Date: 2026-09-15 12:37:16.482400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94fcf6c31f4'
down_revision: Union[str, Sequence[str], None] = '9e998c23caaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therapist_profiles', sa.Column('razorpay_account_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('therapist_profiles', 'razorpay_account_id')
    # ### end Alembic commands ###
