"""add_therapist_marketplace_tables

Revision ID: aed45a4fd845
Revises: 6aacf74cea2b
Create Date: 2026-09-15 11:35:10.986087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aed45a4fd845'
down_revision: Union[str, Sequence[str], None] = '6aacf74cea2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapist_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_photo_url', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('specialisations', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('qualifications', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('certifications', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('min_age_months', sa.Integer(), nullable=True),
    sa.Column('max_age_months', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('session_duration_mins', sa.Integer(), nullable=False),
    sa.Column('session_price_online', sa.Integer(), nullable=True),
    sa.Column('session_price_offline', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_listing_active', sa.Boolean(), nullable=True),
    sa.Column('listing_tier', sa.String(), nullable=True),
    sa.Column('listing_active_until', sa.Date(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_therapist_profiles_email'), 'therapist_profiles', ['email'], unique=True)
    op.create_index(op.f('ix_therapist_profiles_id'), 'therapist_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_therapist_profiles_user_id'), 'therapist_profiles', ['user_id'], unique=True)
    op.create_table('therapist_availability',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('therapist_id', sa.String(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapist_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('therapist_bookings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('therapist_id', sa.String(), nullable=False),
    sa.Column('parent_user_id', sa.String(), nullable=False),
    sa.Column('parent_name', sa.String(), nullable=False),
    sa.Column('parent_email', sa.String(), nullable=False),
    sa.Column('parent_phone', sa.String(), nullable=True),
    sa.Column('child_name', sa.String(), nullable=True),
    sa.Column('child_age_months', sa.Integer(), nullable=True),
    sa.Column('child_condition', sa.String(), nullable=True),
    sa.Column('parent_notes', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.String(), nullable=False),
    sa.Column('scheduled_time', sa.String(), nullable=False),
    sa.Column('duration_mins', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('session_price', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('therapist_notes', sa.Text(), nullable=True),
    sa.Column('razorpay_order_id', sa.String(), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(), nullable=True),
    sa.Column('video_room_id', sa.String(), nullable=True),
    sa.Column('recording_url', sa.String(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapist_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_therapist_bookings_parent_user_id'), 'therapist_bookings', ['parent_user_id'], unique=False)
    op.create_table('therapist_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('booking_id', sa.String(), nullable=False),
    sa.Column('therapist_id', sa.String(), nullable=False),
    sa.Column('parent_user_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['therapist_bookings.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapist_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('therapist_reviews')
    op.drop_index(op.f('ix_therapist_bookings_parent_user_id'), table_name='therapist_bookings')
    op.drop_table('therapist_bookings')
    op.drop_table('therapist_availability')
    op.drop_index(op.f('ix_therapist_profiles_user_id'), table_name='therapist_profiles')
    op.drop_index(op.f('ix_therapist_profiles_id'), table_name='therapist_profiles')
    op.drop_index(op.f('ix_therapist_profiles_email'), table_name='therapist_profiles')
    op.drop_table('therapist_profiles')
    # ### end Alembic commands ###
