"""add preferred_language to child_profiles

Revision ID: b70081a88e41
Revises: ac786af7921b
Create Date: 2026-08-09 21:15:37.076578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70081a88e41'
down_revision: Union[str, Sequence[str], None] = 'ac786af7921b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('child_profiles', sa.Column('preferred_language', sa.String(), nullable=True))
    op.execute("UPDATE child_profiles SET preferred_language = 'English'")
    op.alter_column('child_profiles', 'preferred_language', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('child_profiles', 'preferred_language')
    # ### end Alembic commands ###
