"""Add DevelopmentalSnapshot and DevelopmentalDomain

Revision ID: c6e1103414c8
Revises: ee98c523997d
Create Date: 2026-08-30 23:57:54.663578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e1103414c8'
down_revision: Union[str, Sequence[str], None] = 'ee98c523997d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developmental_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('child_id', sa.String(), nullable=False),
    sa.Column('assessment_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('chronological_age_months', sa.Integer(), nullable=False),
    sa.Column('domain_scores', sa.JSON(), nullable=False),
    sa.Column('next_milestones', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developmental_snapshots_id'), 'developmental_snapshots', ['id'], unique=False)
    op.drop_index(op.f('ix_curated_youtube_videos_id'), table_name='curated_youtube_videos')
    op.drop_index(op.f('ix_curated_youtube_videos_youtube_id'), table_name='curated_youtube_videos')
    op.drop_table('curated_youtube_videos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curated_youtube_videos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('youtube_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('curated_youtube_videos_pkey'))
    )
    op.create_index(op.f('ix_curated_youtube_videos_youtube_id'), 'curated_youtube_videos', ['youtube_id'], unique=True)
    op.create_index(op.f('ix_curated_youtube_videos_id'), 'curated_youtube_videos', ['id'], unique=False)
    op.drop_index(op.f('ix_developmental_snapshots_id'), table_name='developmental_snapshots')
    op.drop_table('developmental_snapshots')
    # ### end Alembic commands ###
