"""add ai_summary to activity session

Revision ID: e2659d8a0077
Revises: f8885b595807
Create Date: 2026-09-20 12:26:28.861691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2659d8a0077'
down_revision: Union[str, Sequence[str], None] = 'f8885b595807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_sessions', sa.Column('ai_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_sessions', 'ai_summary')
    # ### end Alembic commands ###
