"""Add mode to daily_plans

Revision ID: ee98c523997d
Revises: 8c2ac3e0f1b3
Create Date: 2026-08-16 21:59:35.302073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee98c523997d'
down_revision: Union[str, Sequence[str], None] = '8c2ac3e0f1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_plans', sa.Column('mode', sa.String(), server_default='creative', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_plans', 'mode')
    # ### end Alembic commands ###
