"""Add CuratedYouTubeVideo table

Revision ID: f5d35f688b46
Revises: ee98c523997d
Create Date: 2026-08-30 13:25:27.251607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d35f688b46'
down_revision: Union[str, Sequence[str], None] = 'ee98c523997d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curated_youtube_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curated_youtube_videos_id'), 'curated_youtube_videos', ['id'], unique=False)
    op.create_index(op.f('ix_curated_youtube_videos_youtube_id'), 'curated_youtube_videos', ['youtube_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curated_youtube_videos_youtube_id'), table_name='curated_youtube_videos')
    op.drop_index(op.f('ix_curated_youtube_videos_id'), table_name='curated_youtube_videos')
    op.drop_table('curated_youtube_videos')
    # ### end Alembic commands ###
