"""add audio url to booking

Revision ID: f62366689461
Revises: 0b5a62f4c924
Create Date: 2026-09-19 14:13:07.531840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f62366689461'
down_revision: Union[str, Sequence[str], None] = '0b5a62f4c924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therapist_bookings', sa.Column('therapist_audio_url', sa.String(), nullable=True))
    op.add_column('therapist_bookings', sa.Column('therapist_audio_transcript', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('therapist_bookings', 'therapist_audio_transcript')
    op.drop_column('therapist_bookings', 'therapist_audio_url')
    # ### end Alembic commands ###
