"""add category to therapist video

Revision ID: f8885b595807
Revises: 934c5604105e
Create Date: 2026-09-20 09:24:08.201611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8885b595807'
down_revision: Union[str, Sequence[str], None] = '934c5604105e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therapist_videos', sa.Column('category', sa.String(), nullable=False, server_default='General Education'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('therapist_videos', 'category')
    # ### end Alembic commands ###
